### ISSUE TITLE
Wanneer is dit klaar?

### ISSUE THREAD

**Issue by DavyKoravand** [Nick-Caris/slack-app#2]
Ik moet weten wat de sub of the day is bro

**Comment by Besselking** [comment]
https://www.subway.com/nl-nl/menunutrition/menu/sub-of-the-day

**Comment by Besselking** [comment]
@DavyKoravand het is klaar, gebruik [Deno](https://deno.land/) om het te draaien

**Comment by DavyKoravand** [comment]
Hahaha nice.
